Repository oding01/Expense-Tracker, pull requests merged in 2025-02, with the labels that each got.

#18 AnalyzeList의 ProgressBar 퍼센트별 출력
  src/components/Analyze/AnalyzeChoice.tsx
  src/components/Analyze/AnalyzeContainer.tsx
  src/components/Analyze/AnalyzeContext.tsx
  src/components/Analyze/AnalyzeList.tsx
  src/components/store/AnalyzeStore.ts
  src/index.css
  src/types/type.ts
  src/utils/money.ts
Labels: ✨Feature, 🎨Design

#19 main 페이지 쉐도우 및 박스 배경 변경
  src/components/Expense/ExpenseFrame.tsx
  src/components/Recent/MostRecent.tsx
  src/index.css
Labels: 🎨Design

#23 fix: :bug: 카테고리 데이터 추가 및 높이, 위치 조정
  src/components/Input/InputContainer.tsx
  src/components/Input/components/CategorySelect.tsx
  src/constants/categories.ts
Labels: 🛠️Refactor

#24 feat: :sparkles: 입력 페이지 - 확인 버튼 추가
  src/components/Input/components/InputField.tsx
  src/components/Input/components/InputForm.tsx
  src/index.css
Labels: ✨Feature, 🛠️Refactor

#30 feat: :sparkles: 컴포넌트 구조 변경 및 DatePicker 도입
  src/components/Input/InputContainer.tsx
  src/components/Input/components/BaseField.tsx
  src/components/Input/components/DatePickerField.tsx
  src/components/Input/components/InputField.tsx
  src/components/Input/components/InputTypeToggle.tsx
  src/components/Input/components/TextAreaField.tsx
Labels: ✨Feature

#32 test: :white_check_mark: 지출 테이블 테스트
  src/api/api.ts
  supabase/database.types.ts
  supabase/supabase.ts
Labels: ✅Test

#31 feat: :sparkles: 분석 페이지: 날짜 선택시 해당 날짜 데이터만 뜨게끔 수정
  src/Mock/Mock.ts
  src/api/api.ts
  src/components/Analyze/AnalyzeCharts.tsx
  src/components/Analyze/AnalyzeChoice.tsx
  src/components/Analyze/AnalyzeContext.tsx
  src/components/Analyze/AnalyzeList.tsx
  src/components/Analyze/charts/DoughnutChart.tsx
  src/components/store/AnalyzeStore.ts
  src/index.css
  src/types/type.ts
  src/utils/DatePick.tsx
Labels: ✨Feature

#33 fix: :bug: .vscode, extension.json 생기는 것 fix
  .gitignore
  .vscode/extensions.json
Labels: 🔥Bug Fix, ⚙️Setting

#35 feat: :sparkles: account 테이블 생성 및 uid 조인
  supabase/database.types.ts
Labels: ✨Feature

#34 feat: :sparkles: form Validation 추가
  package.json
  pnpm-lock.yaml
  src/api/api.ts
  src/components/Input/InputContainer.tsx
  src/components/Input/components/BaseField.tsx
  src/components/Input/components/DatePickerField.tsx
  src/components/Input/components/InputField.tsx
  src/components/Input/components/InputForm.tsx
  src/components/Input/components/TextAreaField.tsx
  src/types/type.ts
Labels: ✨Feature

#36 feat: :sparkles: Home 차트 추가
  src/Mock/Mock.ts
  src/api/api.ts
  src/components/Analyze/AnalyzeCharts.tsx
  src/components/Analyze/AnalyzeList.tsx
  src/components/Analyze/charts/AnalyzeDoughnutChart.tsx
  src/components/Expense/CategoryChart.tsx
  src/components/Expense/ExpenseChart.tsx
  src/components/Expense/ExpenseContainer.tsx
  src/components/Expense/ExpenseDoughnutChart.tsx
  src/utils/chartColors.ts
  src/utils/dateToKorean.ts
Labels: ✨Feature
